#!/bin/bash

export GRADIO_ANALYTICS_ENABLED=0
export HF_HUB_DISABLE_TELEMETRY=1
export NEXT_TELEMETRY_DISABLED=1
export SE_AVOID_STATS=true
export GOTELEMETRY=off
export DOTNET_CLI_TELEMETRY_OPTOUT=1
